name: Déploiement
on: push
env:
  USERNAME: arielmag
  IMAGE_NAME: deer
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  read-me-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
          readme: "./README.md"
